In [34]:
import numpy as np

In [35]:
a = np.array([1, 2, 3])

In [36]:
a.shape

(3,)

In [37]:
b = np.zeros((3, 5))

In [38]:
type(b)
b.size

15

In [39]:
np.random.seed(6)
np.random.randn(3, 4)

array([[-0.31178367,  0.72900392,  0.21782079, -0.8990918 ],
       [-2.48678065,  0.91325152,  1.12706373, -1.51409323],
       [ 1.63929108, -0.4298936 ,  2.63128056,  0.60182225]])

In [40]:
np.linspace(0, 100, 30)

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [41]:
np.arange(0, 100, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [46]:
def initialization(m, n):
    w = np.random.randn(m, n)
    b = np.ones((m, 1))
    return np.hstack((w, b))

In [47]:
initialization(6, 4)

array([[ 0.42628539, -0.75815703, -0.16236698,  0.72680996,  1.        ],
       [ 0.44408297, -0.85682264,  0.44692842, -1.01464799,  1.        ],
       [-2.1323234 ,  0.17386307,  0.95120126,  0.44189739,  1.        ],
       [ 1.46901739,  1.74951635,  0.35353062, -0.64333729,  1.        ],
       [-0.04723705, -1.44903979, -0.03618977, -0.09084699,  1.        ],
       [ 0.17629034,  1.09462041, -2.12647459,  0.75144883,  1.        ]])