## Broadcasting

In [7]:
import numpy as np

np.random.seed(0)
A = np.random.randint(0, 10, [4, 1])
B = np.ones((1, 3))
A

array([[5],
       [0],
       [3],
       [3]])

In [8]:
B

array([[1., 1., 1.]])

In [9]:
A+B

array([[6., 6., 6.],
       [1., 1., 1.],
       [4., 4., 4.],
       [4., 4., 4.]])